### ISSUE TITLE
Add Support for the Prometheus Remote Read API

### ISSUE THREAD

**Issue by 4n4nd** [AICoE/prometheus-api-client-python#138]
This should enable the user to stream requested metrics from the [Prometheus Server](https://prometheus.io/blog/2019/10/10/remote-read-meets-streaming/#remote-read).

Also, need to add an exporter that can output the stream metrics to Parquet. (Similar to [prom-exporter](https://gitlab.cee.redhat.com/data-hub/prometheus-data-exporter/-/blob/master/prom_data_exporter/writer.py#L126))
@durandom @accorvin @gmfrasca @tumido

**Comment by 4n4nd** [comment]
Ideally we should be able to use the [proto file](https://github.com/thanos-io/thanos/blob/master/pkg/store/storepb/rpc.proto) from Thanos with minimal changes

**Comment by gmfrasca** [comment]
Initial Draft Requirements, pending updates and suggestions from Thanos/Telemetry team:

* User Provided Input:
    - Metric/Label Name
    - Metric Duration
    - Prometheus Configuration containing:
        - Prometheus Endpoint
        - Prometheus Credentials or SA/Bearer Token
   - Storage Destination/Configuration
   
* Reader should be able to be called as a simple script with minimal setup (such that it can be leveraged in shell scripts for use in pipeline utilities)
* Reader should utilize the Prometheus Remote Read API to acquire TSDB data directly, rather than from evaluations of PromQL queries
* Reader should parse the acquired Prometheus Data and format it in a Data Science-friendly format (namely, parquet)
* Reader should properly handle or alert on non-successful retrievals
* Output:
   - Stores results in Parquet Format
   - Possible to use S3 storage endpoint as destination

**Comment by bwplotka** [comment]
Hey, we are exactly working on that with @iNecas here but in Go: https://github.com/thanos-community/obslytics/tree/master/pkg 

Having this in Go actually means we can reuse tons of packages from Prometheus (vs chunk encoding)/

By looking on your draft this tool meets requirements, we planned to produce `parquet` files.

> Reader should parse the acquired Prometheus Data and format it in a Data Science-friendly format (namely, parquet)

The idea is to support even more e.g Arrow Flight gRPC. If you have **any** ideas on other requirements let us know in https://github.com/thanos-community/obslytics/issues. We can guide you and help you contribute even if it means some `Go` coding walk through :hugs: (: 

Let us know if we are missing something. I added outstanding tasks to do here: https://github.com/thanos-community/obslytics/issues

> Reader should properly handle or alert on non-successful retrievals

This one needs some clarifications on what `proper` means (:

**Comment by 4n4nd** [comment]
> We can guide you and help you contribute even if it means some Go coding walk through :hugs: (:

Yeah we don't really have a ton of experience with Go, so some help would be awesome.
> I added outstanding tasks to do here: https://github.com/thanos-community/obslytics/issues

I'll read through the issues and will try to work on something :+1:

**Comment by 4n4nd** [comment]
This issue is being tracked [here](https://projects.engineering.redhat.com/browse/DATAHUB-2331) internally.

**Comment by 4n4nd** [comment]
Since the Remote Read API support was added to the https://github.com/thanos-community/obslytics project, I will close this issue today.
